environment:
  num_envs:
    type: 'int'
    low: 3
    high: 8

algorithm:
  total_timesteps:
    type: 'categorical'
    choices: [15000000, 20000000]

  gae_lambda: 
    type: 'float'
    low: 0.95
    high: 0.99

  n_steps:
    type: 'categorical'
    choices: [320, 400, 480, 560, 640, 720]
  
  learning_rate:
    type: 'float'
    low: 0.0003
    high: 0.002
  
  learning_rate_schedule:
    type: 'categorical'
    choices:
      - type: 'lin'

policy:
  net_arch:
    type: 'categorical'
    choices:
      - pi: [128, 128, 128]
        vf: [128, 128, 128]
      - pi: [256, 256, 256]
        vf: [256, 256, 256]
  
  optimizer_class:
    type: 'categorical'
    choices: ['rmsprop']