environment:
  name: GPUQuadcopterTT
  eval_envname: QuadcopterTT-v0
  num_envs: 323
  normalized_rewards: false
  environment_kwargs:
    trajectory_file: 'trajectory_sine.mat'
    param:
      T: 3.
      dt: 0.004
      max_thrust_factor: 2
    reference_trajectory_horizon: 0.3
    normalized_actions: true
    normalized_observations: true
    intermittent_starts: true
    alpha_cost: 5.693
    alpha_action_cost: 5.693
    alpha_terminal_cost: 0.3166

algorithm:
  name: PPO
  total_timesteps: 40000000
  save_every_timestep: 30000000
  algorithm_kwargs:
    gamma: 0.9984539792726858
    gae_lambda: 0.99
    ent_coef: 0.
    vf_coef: 0.5
    normalize_advantage: false
    max_grad_norm: 0.009753530446987978
    learning_rate: 0.000011642278771351222
    learning_rate_schedule:
      type: kla
      target_kl: null
    n_steps: 116
    n_epochs: 5
    batch_size: 0.25
    clip_range: 0.1

policy:
  save_prefix: model
  policy_kwargs:
    net_arch:
      pi: [1024, 1024, 1024]
      vf: [1024, 1024, 1024]
    activation_fn: relu
    optimizer_class: rmsprop
    log_std_init: -1.51946188846120455
    ortho_init: true
