criteria:
  type: 'final_err'
  num_episodes: 50

algorithm:
  n_steps:
    type: 'int'
    low: 60
    high: 600
    log: True

  n_epochs:
    type: 'categorical'
    choices: [5, 10]
  
  max_grad_norm:
    type: 'float'
    low: 0.001
    high: 1
    log: True

  learning_rate:
    type: 'float'
    low: 0.00001
    high: 0.001
    log: True