criteria:
  type: 'final_err'
  num_episodes: 50

environment:
  num_envs:
    type: 'int'
    low: 500
    high: 1000
    log: True
  
  reference_trajectory_horizon:
    type: 'categorical'
    choices: [0.125, 0.5]

algorithm:
  n_steps:
    type: 'int'
    low: 50
    high: 250
    log: True
  
  batch_size:
    type: 'categorical'
    choices: [0.25, 0.5]

  n_epochs:
    type: 'categorical'
    choices: [5, 10]
  
  learning_rate:
    type: 'float'
    low: 0.00001
    high: 0.001
    log: True

  ent_coef:
    type: 'float'
    low: 0.000001
    high: 0.01
    log: True

policy:
  log_std_init:
    type: 'float'
    low: -3.
    high: 0.