criteria:
  type: 'final_err'
  num_episodes: 20

environment:
  num_envs:
    type: 'int'
    low: 1
    high: 5

algorithm:
  n_steps:
    type: 'int'
    low: 200
    high: 800

  n_epochs:
    type: 'int'
    low: 1
    high: 20
  
  learning_rate:
    type: 'float'
    low: 0.00002
    high: 0.0006
  
  max_grad_norm:
    type: 'float'
    low: 0.1
    high: 5
  
  clip_range:
    type: 'float'
    low: 0.05
    high: 0.5
  
  vf_coef:
    type: 'float'
    low: 0.1
    high: 1

policy:
  log_std_init:
    type: 'float'
    low: -4
    high: -2