environment:
  num_envs:
    type: 'int'
    low: 1
    high: 5

algorithm:
  gae_lambda: 
    type: 'float'
    low: 0.95
    high: 0.99
  
  n_steps:
    type: 'categorical'
    choices: [50, 100, 150]
  
  learning_rate:
    type: 'float'
    low: 0.0003
    high: 0.0015
  
  learning_rate_schedule:
    type: 'categorical'
    choices:
      - null
      - type: 'lin'

policy:
  net_arch:
    type: 'categorical'
    choices:
      - pi: [32, 32]
        vf: [32, 32]
      - pi: [64, 64]
        vf: [64, 64]
  
  optimizer_class:
    type: 'categorical'
    choices: ['rmsprop', 'rmsproptflike']