criteria:
  type: 'final_err'
  num_episodes: 50

environment:
  num_envs:
    type: 'int'
    low: 300
    high: 900
    log: True
  
  dt:
    type: 'categorical'
    choices: [0.005, 0.004]

algorithm:
  n_steps:
    type: 'int'
    low: 10
    high: 100
    log: True

  batch_size:
    type: 'categorical'
    choices: [0.1, 0.2]

  n_epochs:
    type: 'categorical'
    choices: [5, 10]
  
  learning_rate:
    type: 'float'
    low: 0.00001
    high: 0.001
    log: True

  ent_coef:
    type: 'float'
    low: 0.000001
    high: 0.01
    log: True

  clip_range:
    type: 'categorical'
    choices: [0.05, 0.1]

policy:
  log_std_init:
    type: 'float'
    low: -3
    high: 0.