criteria:
  type: 'final_err'
  num_episodes: 20

environment:
  num_envs:
    type: 'int'
    low: 100
    high: 500

  alpha_cost:
    type: 'float'
    low: 0.1
    high: 10
    log: True

  alpha_terminal_cost:
    type: 'float'
    low: 0.1
    high: 10
    log: True

algorithm:
  n_steps:
    type: 'int'
    low: 100
    high: 500

  n_epochs:
    type: 'int'
    low: 1
    high: 20
    log: True

  learning_rate:
    type: 'float'
    low: 0.00002
    high: 0.002
    log: True

  ent_coef:
    type: 'float'
    low: 0.000001
    high: 0.1
    log: True

  max_grad_norm:
    type: 'float'
    low: 0.1
    high: 5
  
  clip_range:
    type: 'float'
    low: 0.05
    high: 0.5

policy:
  log_std_init:
    type: 'float'
    low: -4
    high: -2