criteria:
  type: 'final_err'
  num_episodes: 20

environment:
  num_envs:
    type: 'int'
    low: 20
    high: 100
  
  dt:
    type: 'categorical'
    choices: [0.002, 0.003, 0.004]

algorithm:
  gamma:
    type: 'float'
    low: 0.99
    high: 0.9999
    log: True

  gae_lambda:
    type: 'float'
    low: 0
    high: 1

  n_steps:
    type: 'int'
    low: 30
    high: 300

  n_epochs:
    type: 'int'
    low: 1
    high: 20
    log: True
  
  learning_rate:
    type: 'float'
    low: 0.00001
    high: 0.001
    log: True
  
  max_grad_norm:
    type: 'float'
    low: 0.1
    high: 5
  
  clip_range:
    type: 'float'
    low: 0.05
    high: 0.5

policy:
  log_std_init:
    type: 'float'
    low: -4
    high: -2
    
