environment:
  name: QuadcopterTTDecomposition-v0
  eval_envname: QuadcopterTTDecomposition-v0
  num_envs: 3
  normalized_rewards: false
  environment_kwargs:
    trajectory_file: trajectory_sine.mat
    param:
      T: 3.
      dt: 0.004
      max_thrust_factor: 2
    reference_trajectory_horizon: 0.4
    normalized_actions: true
    normalized_observations: true
    intermittent_starts: false
    alpha_cost: 5.693
    alpha_action_cost: 5.693
    alpha_terminal_cost: 0.3166

algorithm:
  name: PPO
  total_timesteps: 15000000
  save_every_timestep: 500000
  max_no_improvement_evals: 4
  min_evals: 1
  improve_tol: -0.1
  eval_offline: false
  n_eval_episodes: 100
  algorithm_kwargs:
    gamma: 0.9984539792726858
    gae_lambda: 0.99
    ent_coef: 0.
    vf_coef: 0.5
    normalize_advantage: false
    max_grad_norm: 0.9216909281395821
    learning_rate: 0.00036558379071618247
    learning_rate_schedule:
      type: lin
    n_steps: 281
    n_epochs: 7
    batch_size: 843
    clip_range: 0.2

decomposition:
  independent_states: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  in_tree:
    - [3, 1]
    - [3, 1]
    - [3, 1]
    - [-1, 1]
  in_st_map:
    - [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1]
    - [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1]
    - [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1]
    - [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1]

policy:
  save_prefix: model
  policy_kwargs:
    net_arch:
      pi:
        - - [0,1,2]
          - [640,640,640]
        - - [3]
          - [256,256,256]
    activation_fn: relu
    optimizer_class: rmsprop
    log_std_init: -2.067521056483639
    ortho_init: true
