environment:
  num_envs:
    type: 'int'
    low: 1
    high: 5

algorithm:
  gae_lambda: 
    type: 'float'
    low: 0.95
    high: 0.99

  n_steps:
    type: 'categorical'
    choices: [128, 256]
  
  learning_rate:
    type: 'float'
    low: 0.0003
    high: 0.002
  
  learning_rate_schedule:
    type: 'categorical'
    choices:
      - type: null
      - type: 'lin'

policy:
  net_arch:
    type: 'categorical'
    choices:
      - pi: [128, 128]
        vf: [128, 128]
      - pi: [256, 256]
        vf: [256, 256]
  
  optimizer_class:
    type: 'categorical'
    choices: ['rmsprop']