environment:
  name: 'GPUQuadcopter'
  eval_envname: 'Quadcopter-v0'
  num_envs: 500
  normalized_rewards: False
  environment_kwargs:
    normalized_actions: True
    normalized_observations: True
    dt: 0.004
    alpha_cost: 1.224
    alpha_terminal_cost: 1.99

algorithm:
  name: 'PPO'
  total_timesteps: 120000000
  save_every_timestep: 90000000
  algorithm_kwargs:
    gamma: 0.9995
    gae_lambda: 0.99
    ent_coef: 0.
    vf_coef: 0.5
    normalize_advantage: False
    max_grad_norm: 0.9217
    learning_rate: 0.0002003
    n_steps: 600
    n_epochs: 6
    batch_size: 75000
    clip_range: 0.2
    device: 'cuda'

policy:
  save_prefix: 'model'
  policy_kwargs:
    net_arch:
      pi: [256, 256, 256]
      vf: [256, 256, 256]
    activation_fn: 'relu'
    optimizer_class: 'rmsprop'
    log_std_init: -0.4277
    ortho_init: True
