criteria:
  type: 'final_err'
  num_episodes: 20

environment:
  num_envs:
    type: 'int'
    low: 100
    high: 500

algorithm:
  gae_lambda:
    type: 'float'
    low: 0
    high: 1

  n_steps:
    type: 'int'
    low: 30
    high: 300

  n_epochs:
    type: 'int'
    low: 1
    high: 20
    log: True
  
  learning_rate:
    type: 'float'
    low: 0.00001
    high: 0.001
    log: True

  ent_coef:
    type: 'float'
    low: 0.000001
    high: 0.01
    log: True

policy:
  log_std_init:
    type: 'float'
    low: -4
    high: -2