criteria:
  type: 'final_err'
  num_episodes: 50

algorithm:
  type: 'int'
    low: 50
    high: 500
    log: True

  n_epochs:
    type: 'categorical'
    choices: [5, 10]
  
  batch_size:
    type: 'categorical'
    choices: [0.1, 0.25, 0.5]
  
  learning_rate:
    type: 'categorical'
    choices: [0.00002, 0.0001]

  max_grad_norm:
    type: 'float'
    low: 0.01
    high: 1
    log: True

policy:
  log_std_init:
    type: 'categorical'
    choices: [-2, -1, 0]