criteria:
  type: 'final_err'
  num_episodes: 50

environment:
  num_envs:
    type: 'int'
    low: 600
    high: 1800
    log: True

algorithm:
  n_steps:
    type: 'int'
    low: 50
    high: 250
    log: True

  n_epochs:
    type: 'categorical'
    choices: [5, 10, 15]
  
  learning_rate:
    type: 'float'
    low: 0.00001
    high: 0.001
    log: True
  
  clip_range:
    type: 'categorical'
    choices: [0.05, 0.1]

  ent_coef:
    type: 'float'
    low: 0.000001
    high: 0.01
    log: True

policy:
  log_std_init:
    type: 'float'
    low: -0.5
    high: 0.5