criteria:
  type: 'final_err'
  num_episodes: 20

environment:
  num_envs:
    type: 'int'
    low: 100
    high: 1000
  
  dt:
    type: 'categorical'
    choices: [0.001, 0.002, 0.003, 0.004]

algorithm:
  gae_lambda:
    type: 'float'
    low: 0
    high: 1

  n_steps:
    type: 'int'
    low: 30
    high: 300

  n_epochs:
    type: 'int'
    low: 1
    high: 100
    log: True
  
  batch_size:
    type: 'int'
    low: 1000
    high: 100000
    log: True
  
  learning_rate:
    type: 'float'
    low: 0.00002
    high: 0.0006
  
  max_grad_norm:
    type: 'float'
    low: 0.1
    high: 5
  
  clip_range:
    type: 'float'
    low: 0.05
    high: 0.5
  
  vf_coef:
    type: 'float'
    low: 0.1
    high: 1

policy:
  log_std_init:
    type: 'float'
    low: -4
    high: -2
    
