criteria:
  type: 'final_err'
  num_episodes: 50

environment:
  num_envs:
    type: 'int'
    low: 400
    high: 1200
    log: True

algorithm:
  n_steps:
    type: 'int'
    low: 40
    high: 400
    log: True

  n_epochs:
    type: 'categorical'
    choices: [5, 10, 15]
  
  learning_rate:
    type: 'float'
    low: 0.00001
    high: 0.001
    log: True
  
  ent_coef:
    type: 'float'
    low: 0.000001
    high: 0.1
    log: True

policy:
  log_std_init:
    type: 'float'
    low: -3
    high: 0