criteria:
  type: 'final_err'
  num_episodes: 50

environment:
  num_envs:
    type: 'int'
    low: 400
    high: 1200
    log: True

algorithm:
  n_steps:
    type: 'int'
    low: 40
    high: 400
    log: True

  n_epochs:
    type: 'categorical'
    choices: [2, 5, 10]
  
  learning_rate:
    type: 'float'
    low: 0.00001
    high: 0.001
    log: True
  
  learning_rate_schedule:
    type: 'categorical'
    choices:
      - type: 'kla'
        target_kl: 0.0025
      - type: 'kla'
        target_kl: 0.005
      - type: 'kla'
        target_kl: 0.0075
  
  ent_coef:
    type: 'float'
    low: 0.000001
    high: 0.01
    log: True

policy:
  log_std_init:
    type: 'float'
    low: -3
    high: 0