criteria:
  type: 'final_err'
  num_episodes: 50

algorithm:
  n_epochs:
    type: 'categorical'
    choices: [5, 10]
  
  batch_size:
    type: 'categorical'
    choices: [0.1, 0.25, 0.5]
  
  learning_rate:
    type: 'float'
    low: 0.00001
    high: 0.001
    log: True

  max_grad_norm:
    type: 'float'
    low: 0.01
    high: 1
    log: True