criteria:
  type: 'final_err'
  num_episodes: 50

environment:
  num_envs:
    type: 'int'
    low: 500
    high: 2000
    log: True

algorithm:
  n_steps:
    type: 'int'
    low: 25
    high: 250

  n_epochs:
    type: 'categorical'
    choices: [10, 15, 20]
  
  batch_size:
    type: 'categorical'
    choices: [0.01, 0.05, 0.1, 0.25]
  
  learning_rate:
    type: 'float'
    low: 0.00001
    high: 0.001
    log: True
  
  ent_coef:
    type: 'float'
    low: 0.000001
    high: 0.01
    log: True

policy:
  log_std_init:
    type: 'float'
    low: -3
    high: 0