environment:
  name: QuadcopterTT-v0
  num_envs: 3
  normalized_rewards: false
  environment_kwargs:
    trajectory_file: 'trajectory_figure8_wider.mat'
    param:
      dt: 0.006
      T: 6.
      max_thrust_factor: 2
    fixed_starts: false
    reference_trajectory_horizon: 1.2
    normalized_actions: true
    normalized_observations: true
    intermittent_starts: false
    alpha_cost: 5.693
    alpha_action_cost: 1.1386
    alpha_terminal_cost: 0.3166

algorithm:
  name: PPO
  total_timesteps: 30000000
  save_every_timestep: 30000000
  algorithm_kwargs:
    gamma: 0.9984539792726858
    gae_lambda: 0.99
    ent_coef: 0.
    vf_coef: 0.5
    normalize_advantage: False
    max_grad_norm: 0.9216909281395821
    learning_rate: 0.00036558379071618247
    learning_rate_schedule:
      type: lin
    n_steps: 281
    n_epochs: 7
    batch_size: 843
    clip_range: 0.2

policy:
  save_prefix: model
  policy_kwargs:
    net_arch:
      pi: [256, 256, 256]
      vf: [256, 256, 256]
    activation_fn: relu
    optimizer_class: rmsprop
    log_std_init: -2.067521056483639
    ortho_init: true
