environment:
  name: GPUQuadcopterDecomposition
  eval_envname: QuadcopterDecomposition-v0
  num_envs: 646
  normalized_rewards: false
  environment_kwargs:
    param:
      dt: 0.004
    normalized_actions: true
    normalized_observations: true
    alpha_cost: 1.223633355917235
    alpha_terminal_cost: 1.9898048601277891

algorithm:
  name: PPO
  total_timesteps: 30000000
  save_every_timestep: 200000
  min_evals: 20
  max_no_improvement_evals: 10
  n_eval_episodes: 200
  algorithm_kwargs:
    gamma: 0.9984539792726858
    gae_lambda: 0.99
    ent_coef: 0.009871730492222603
    vf_coef: 0.5
    normalize_advantage: false
    max_grad_norm: 0.9216909281395821
    learning_rate: 1.5283609473524498e-05
    learning_rate_schedule:
      type: kla
      target_kl: null
    n_steps: 116
    n_epochs: 5
    batch_size: 18734
    clip_range: 0.1

decomposition:
  independent_states: [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  in_tree:
    - [2, 1]
    - [2, 1]
    - [-1, 1]
    - [-1, 2]
  in_st_map:
    - [0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1]
    - [0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1]
    - [0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1]
    - [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1]

policy:
  save_prefix: model
  type: 'DecompositionMlpPolicy'
  policy_kwargs:
    net_arch:
      pi:
        - - [0, 1]
          - [2048,2048,2048]
        - - [2]
          - [1024,1024,1024]
        - - [3]
          - [1024,1024,1024]
    activation_fn: relu
    optimizer_class: rmsprop
    log_std_init: -0.01946188846120455
    ortho_init: true
