environment:
  name: 'Unicycle-v0'
  num_envs: 1
  normalized_rewards: False
  environment_kwargs:
    nonlinear_cost: False
    normalized_actions: True
    normalized_observations: True
    dt: 0.004
    T: 3.
    alpha_cost: 0.79
    alpha_action_cost: 0.79
    alpha_terminal_cost: 0.1

algorithm:
  name: 'PPO'
  total_timesteps: 15000000
  save_every_timestep: 10000000
  algorithm_kwargs:
    gamma: 0.9995
    gae_lambda: 0.99
    ent_coef: 0.
    vf_coef: 0.5
    normalize_advantage: False
    max_grad_norm: 0.9216909281395821
    learning_rate: 0.00036558379071618247
    learning_rate_schedule: 
      type: 'lin'
    n_steps: 320
    n_epochs: 7
    batch_size: null
    clip_range: 0.2

policy:
  save_prefix: 'model'
  policy_kwargs:
    net_arch:
      pi: [256, 256, 256]
      vf: [256, 256, 256]
    activation_fn: 'relu'
    optimizer_class: 'rmsprop'
    log_std_init: -2.067521056483639
    ortho_init: True