criteria:
  type: 'final_err'
  num_episodes: 50

environment:
  num_envs:
    type: 'int'
    low: 3
    high: 8

  alpha_cost:
    type: 'float'
    low: 1
    high: 50
    log: True

  alpha_terminal_cost:
    type: 'float'
    low: 0.05
    high: 5
    log: True

algorithm:
  n_steps:
    type: 'int'
    low: 512
    high: 2048
  
  n_epochs:
    type: 'int'
    low: 6
    high: 15
  
  learning_rate:
    type: 'float'
    low: 0.00002
    high: 0.002
    log: True