environment:
  name: Unicycle-v0
  num_envs: 4
  normalized_rewards: false
  environment_kwargs:
    nonlinear_cost: false
    normalized_actions: true
    normalized_observations: true
    dt: 0.004
    T: 3.
    alpha_cost: 39.901375931841876
    alpha_action_cost: 11.376743863238083
    alpha_terminal_cost: 0.08743780386969448

algorithm:
  name: PPO
  total_timesteps: 15000000
  save_every_timestep: 15000000
  algorithm_kwargs:
    gamma: 0.9984539792726858
    gae_lambda: 0.99
    ent_coef: 0.
    vf_coef: 0.5
    normalize_advantage: false
    max_grad_norm: 0.9216909281395821
    learning_rate: 0.00020881450374010674
    learning_rate_schedule:
      type: lin
    n_steps: 987
    n_epochs: 10
    batch_size: 3948
    clip_range: 0.2

policy:
  save_prefix: model
  policy_kwargs:
    net_arch:
      pi: [256, 256, 256]
      vf: [256, 256, 256]
    activation_fn: relu
    optimizer_class: rmsprop
    log_std_init: -2.067521056483639
    ortho_init: true
