criteria:
  type: 'final_err'
  num_episodes: 20

environment:
  num_envs:
    type: 'int'
    low: 1
    high: 5

  alpha_cost:
    type: 'float'
    low: 0.05
    high: 50
    log: True
  
  alpha_action_cost:
    type: 'float'
    low: 0.05
    high: 50
    log: True

  alpha_terminal_cost:
    type: 'float'
    low: 0.05
    high: 50
    log: True

algorithm:
  n_steps:
    type: 'int'
    low: 64
    high: 1024
  
  n_epochs:
    type: 'int'
    low: 1
    high: 10
  
  learning_rate:
    type: 'float'
    low: 0.00002
    high: 0.002
    log: True