criteria:
  type: 'final_err'
  num_episodes: 20

environment:
  num_envs:
    type: 'int'
    low: 1
    high: 5

  alpha_terminal_cost:
    type: 'float'
    low: 0.01
    high: 10
    log: True

algorithm:
  n_steps:
    type: 'int'
    low: 64
    high: 2048
    log: True
  
  n_epochs:
    type: 'int'
    low: 1
    high: 20
  
  learning_rate:
    type: 'float'
    low: 0.00002
    high: 0.002
    log: True
  
  max_grad_norm:
    type: 'float'
    low: 0.1
    high: 5
  
  ent_coef:
    type: 'float'
    low: 0.00001
    high: 0.01
    log: True

policy:
  log_std_init:
    type: 'float'
    low: -4
    high: -2